### ISSUE TITLE
In Foundry v.0.8.9 updating from module v.1.8.6 to v.1.8.91 disables the ability to use Better Roll Tables

### ISSUE THREAD

**Issue by magispitt** [ultrakorne/better-rolltables#158]
![image](https://user-images.githubusercontent.com/96706608/147424908-d6fc3e72-7794-411f-9ee6-14b6356aa4a9.png)

I am uncertain if this is related to the advertised interface updates

![image](https://user-images.githubusercontent.com/96706608/147424882-107bd06c-6e4a-4617-8f3d-308e094239cf.png)

**Comment by DanielBoettner** [comment]
@magispitt 

Does the browser console give any errors?

**Comment by magispitt** [comment]
> @magispitt
> 
> Does the browser console give any errors?

I see the following errors after pressing F12:

![image](https://user-images.githubusercontent.com/96706608/147511372-74e84498-0cc6-4117-8ca4-200945146214.png)

**Comment by DanielBoettner** [comment]
Lets start from the bottom. 
## Handlebars issue

Could you click on the small arrow next to `d` and post a screenshot of the handlebars issue?
I can imagine that there is a bug regarding filepaths (windows/linux).

## updateSpellCache
The line in question tries to get the default spell compendium.

```js
const defaultPack = game.settings.get(MODULE.ns, BRTCONFIG.SPELL_COMPENDIUM_KEY);
      if (!pack || pack === defaultPack) {
        const spellCompendium = game.packs.get(defaultPack);
        const spellCompendiumIndex = await spellCompendium.getIndex({ fields: ['data.level', 'img'] });
```
In the settings we set the default compendium to `pf2e.spells-srd`.
Could you make sure that this compendium exists? Or if you changed the compendium, make sure this one exists.
Either way, I will try to add a check to above code that checks if a `spellCompendium` was loaded successfully. 
## Item issue
The error at the top would suggest that maybe the structure of items we expect is 5e but we get PF2E.
But that could be an unrelated error.

**Comment by magispitt** [comment]
> Lets start from the bottom.
> 
> ## Handlebars issue
> Could you click on the small arrow next to `d` and post a screenshot of the handlebars issue? I can imagine that there is a bug regarding filepaths (windows/linux).
> 
> ## updateSpellCache
> The line in question tries to get the default spell compendium.
> 
> ```js
> const defaultPack = game.settings.get(MODULE.ns, BRTCONFIG.SPELL_COMPENDIUM_KEY);
>       if (!pack || pack === defaultPack) {
>         const spellCompendium = game.packs.get(defaultPack);
>         const spellCompendiumIndex = await spellCompendium.getIndex({ fields: ['data.level', 'img'] });
> ```
> 
> In the settings we set the default compendium to `pf2e.spells-srd`. Could you make sure that this compendium exists? Or if you changed the compendium, make sure this one exists. Either way, I will try to add a check to above code that checks if a `spellCompendium` was loaded successfully.
> 
> ## Item issue
> The error at the top would suggest that maybe the structure of items we expect is 5e but we get PF2E. But that could be an unrelated error.

Alright, for the handlebars error the drop-down menu reveals this:

![image](https://user-images.githubusercontent.com/96706608/147608234-c341d959-ea24-4c3b-b9d1-37f620410763.png)

**Comment by DanielBoettner** [comment]
You could test with PF2e world.
Did you check the settings for BetterRolltables if you can set the default spell compendium?

Please try the following.

* Press `[F12]` to open the console

put in the following into the console (bottom part, if you don't see it hit `[Esc]`)
* `game.system.id` an press `[Enter]`

I would like to know what that says. Because I just guessed PF2E as a system because 
I read something with `ItemPF`. So if this doesn't say `pf2e` that is likely the problem.

So far in the code we only take care of `PF2E`. What exactly changed that it worked
before with PF1 is another question.

* copy this into the console 
  * `game.settings.get('better-rolltables', 'default-spell-compendium')` and press `[Enter]`
  * This should give you some kind of textstring like `pf1.spells`
 
If the above says `undefined` or `null` or something.
* go into the settings
* go to the Better Rolltable Settings
* Check or select the spell compendium (some compendium with spells, preferably PF1 spells)
* check again via console `game.settings.get('better-rolltables', 'default-spell-compendium')`

**Comment by DanielBoettner** [comment]
Please test the latest release.
This should fix your problem.

Please be aware that BetterRolltables does not officially support PF1.
There are likely more errors.

**Comment by magispitt** [comment]
> You could test with PF2e world. Did you check the settings for BetterRolltables if you can set the default spell compendium?
> 
> Please try the following.
> 
> * Press `[F12]` to open the console
> 
> put in the following into the console (bottom part, if you don't see it hit `[Esc]`)
> 
> * `game.system.id` an press `[Enter]`
> 
> I would like to know what that says. Because I just guessed PF2E as a system because I read something with `ItemPF`. So if this doesn't say `pf2e` that is likely the problem.
> 
> So far in the code we only take care of `PF2E`. What exactly changed that it worked before with PF1 is another question.
> 
> * copy this into the console
>   
>   * `game.settings.get('better-rolltables', 'default-spell-compendium')` and press `[Enter]`
>   * This should give you some kind of textstring like `pf1.spells`
> 
> If the above says `undefined` or `null` or something.
> 
> * go into the settings
> * go to the Better Rolltable Settings
> * Check or select the spell compendium (some compendium with spells, preferably PF1 spells)
> * check again via console `game.settings.get('better-rolltables', 'default-spell-compendium')`

This is on the v.1.8.91 version, I see you have kindly updated the system but I will conduct the requested tests on this version first -- the module appears to work on the Pathfinder 2e system, as you suggested

![image](https://user-images.githubusercontent.com/96706608/147717987-13cea3a7-4966-495d-be12-87d5a2484ec8.png)

**Comment by magispitt** [comment]
> Please test the latest release. This should fix your problem.
> 
> Please be aware that BetterRolltables does not officially support PF1. There are likely more errors.

Alright unfortunately after loading the new update I see this error for a few seconds before it automatically dissapears:

![image](https://user-images.githubusercontent.com/96706608/147718952-9a941061-7f82-4638-86d8-13bf1896d513.png)

**Comment by DanielBoettner** [comment]
The error appears cause the thing the error suggests happend.
That is because.
In the code we default to `dnd5e.spells`.

For PF2e we do
```js 
 if (game.system.id === 'pf2e') {
            defaultLootSheet = 'pf2e.LootSheetNPC';
            defaultSpellCompendium = 'pf2e.spells-srd';

            BRTCONFIG.QUANTITY_PROPERTY_PATH = 'data.quantity.value';
            BRTCONFIG.PRICE_PROPERTY_PATH = 'data.price.value';
            BRTCONFIG.SPELL_LEVEL_PATH = 'data.level.value';
            BRTCONFIG.ITEM_LOOT_TYPE = 'treasure';
            // pf2e scroll is "Scroll of 1st-level Spell"
            BRTCONFIG.SCROLL_REGEX = /\s*Scroll\s*of\s*(\d+)/gi;
        }
```
You could try to set the compendium  to `pf1.spells` in the settings.
In the below image you made, that would be the second line.

![image](https://user-images.githubusercontent.com/96706608/147718478-53b34d2d-6380-4d9a-aa34-9113988b150e.png)

I tried to get conformation on the PF1 structure on discord, but no response yet.
