### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by MSAbaddon** [ultrakorne/better-rolltables#33]
- Support automatic scroll generation for Pathfinder 2e
- Extend the scroll generation function to wands
- Implement a way to filter items from the table and only use the filtered items for rolls, e.g. using the item level. This would allow a DM to manage item wishlists of players using the module without having to create separate tables for every level.
- Add an option to make "draw without replacement" affect a sub table instead of the main table

**Comment by ultrakorne** [comment]
> Support automatic scroll generation for Pathfinder 2e
mmm this should work. i will double check

> Extend the scroll generation function to wands
I might think how to generalize this

> Implement a way to filter items from the table and only use the filtered items for rolls, e.g. using the item level. This would allow a DM to manage item wishlists of players using the module without having to create separate tables for every level.
using the item level could be a way to also generalize the scrolls. will think about this one.

>Add an option to make "draw without replacement" affect a sub table instead of the main table
for the last point, if the sub tables has draw without replacement set it should be honored

**Comment by MSAbaddon** [comment]
Hi,
thanks for the reply.
I tried the scroll functionality using DnD5e with only the better rolltables module enabled:
![image](https://user-images.githubusercontent.com/66370966/84575750-ecaf1280-adaf-11ea-8306-9c52be6dae53.png)

I also tried the draw without replacement functionality, again no other module activated:
![image](https://user-images.githubusercontent.com/66370966/84575805-529b9a00-adb0-11ea-9626-d9beefb8abbb.png)

**Comment by ultrakorne** [comment]
@MSAbaddon you have to change the table type to loot, I didnt want to override any vanilla functionality by default and allow users to still use normal tables if they please. I want the module to be as little intrusive as possible.

the documentation on the module is not the best at the moment, and since I m doing some big changes that will make some stuff easier I am waiting to update the doc with new videos.

**Comment by MSAbaddon** [comment]
Thanks for the clarification.
Works fine now with DnD5e.
Unfortunately Pathfinder 2e still doesn't change the scroll. Draw without replacement does not work either.
![image](https://user-images.githubusercontent.com/66370966/84581207-f69c3a00-adde-11ea-908f-48ed5d106ed8.png)
![image](https://user-images.githubusercontent.com/66370966/84581217-1cc1da00-addf-11ea-9deb-b75dcab862d0.png)

**Comment by ultrakorne** [comment]
@MSAbaddon I will check about the scrolls in pf2, it used to work.

about the replacement, when no more options are selectable it will reset the replacements. because there is multi rolls and table nesting i decided that would be difficult to track and realize that a table is selecting none because you forgot to reset.

If might still be bugged, but when nothing to draw is found the table will be resetted automatically. I will double check

**Comment by MSAbaddon** [comment]
Hi,
thanks again for the reply and your infos.
Got the draw without replacement working - both the main and the sub table need to be defined as loot tables and both need to have draw with replacement unchecked 👍

**Comment by ultrakorne** [comment]
there was a bug in the draw with replacement not working correctly when generating loot to chat. should be fixed now.

Feel free to open new issues, but have 1 issue being 1 topic

**Comment by MSAbaddon** [comment]
Ok, thanks for the info.
Shall I open issues for the other suggestions as reminders for you?
