### ISSUE TITLE
"/" character is not supported inside @price tags

### ISSUE THREAD

**Issue by Pyroman2xxx** [ultrakorne/better-rolltables#56]
Great mod!

This used to work as a "text" item:
Potion of Healing @Compendium[dnd5e.items] @price[((1d6+1)*10)/2]

It now finds and generates the item from the compendium but the '@price' no longer does anything. Is this intended behavior? If so, I need a way to dynamically override prices from the compendiums.

**Comment by ultrakorne** [comment]
I updated in the last hotfix the regular expression because it had severe performance issues and the new one i think does not support the character "/" inside the @price[] tag so that broke your formula.

I will add the division "/" character back in a next update (but probably for foundry 0.7) in the meantime you should be able to make your table work by using  `@price[(1d6+1)*5]`

**Comment by Pyroman2xxx** [comment]
> I updated in the last hotfix the regular expression because it had severe performance issues and the new one i think does not support the character "/" inside the @price[] tag so that broke your formula.

Ah that makes sense. Thank you!

**Comment by ultrakorne** [comment]
actually also parentesis ( ) inside the formula do not work. i will hotfix it tonight probably

**Comment by ultrakorne** [comment]
will be fixed in incoming 1.5.2
