### ISSUE TITLE
Multiple Items no longer stacking in LootSheet5eNPC

### ISSUE THREAD

**Issue by Wade0004** [ultrakorne/better-rolltables#81]
IDK if this is a issue with Better Roll Tables or LootSheet5eNPC, but it used to work that items would stack when added to character, but now they don't:
![Capture](https://user-images.githubusercontent.com/74107522/123292832-aadf9e80-d4d0-11eb-915c-cdf0afffe09d.PNG)

They DO however still stack in chat if you just "roll" and not "generate loot"

![Capture2](https://user-images.githubusercontent.com/74107522/123292955-c5b21300-d4d0-11eb-888d-ac6a9745b6a3.PNG)

**Comment by ultrakorne** [comment]
will have a look, this could be a bug in 0.8x

**Comment by DanielBoettner** [comment]
Likely an issue with lootsheetnpce5e

The check currently isn't [active in the code](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/blob/d492cbb555af313e9a20cc2e2be29e1b5a010ab5/lootsheetnpc5e.js#L301) at least for updatingMerchants.

I think I handled that in my module https://github.com/DanielBoettner/fvtt-loot-populator-npc-5e but didn't specifically test it.
If you have a lootsheet, that has the option set to stack (should be visible when picking merchant instead of loot) I think I respect that when populating on drop.

Don't know if that helps.

**Comment by DanielBoettner** [comment]
Tested it, and lootsheet itself respect stacking.
We'll have to investigate this.

**Comment by ultrakorne** [comment]
should be fixed in 1.6.10

**Comment by Wade0004** [comment]
Confirmed!

Thank you so much!
